[package]
name = "simple-https-tunnel"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.23"
log = "0.4.22"
serde = "1.0.215"
tokio = { version = "1.42.0", features = ["full"] }
tokio-tls = "0.3.1"
tokio-utils = "0.1.2"
